import { spawn } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
const expected = ["connect_status","observe_local","inspect_entity","describe_prototype","can_place","walk_to","mine","place_entity","craft_items","insert_items","extract_items","set_recipe","rotate_entity","build_plan","start_research","stop"].sort();
const cwd = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."); const entry = process.env.MCP_ENTRY ?? "src/cli.ts";
const child = spawn(entry.endsWith(".ts") ? "npx" : "node", entry.endsWith(".ts") ? ["tsx", entry, "mcp"] : [entry, "mcp"], { cwd, stdio: ["pipe", "pipe", "pipe"], env: { ...process.env, HOME: path.join(cwd, ".offline-home") } });
let buffer = "", next = 1; const pending = new Map<number, (v: any) => void>();
child.stdout.on("data", (data) => { buffer += data; let at; while ((at = buffer.indexOf("\n")) >= 0) { const line = buffer.slice(0, at); buffer = buffer.slice(at + 1); if (!line) continue; const message = JSON.parse(line); pending.get(message.id)?.(message); pending.delete(message.id); } });
const request = (method: string, params?: unknown) => new Promise<any>((resolve, reject) => { const id = next++; pending.set(id, resolve); child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n"); setTimeout(() => reject(new Error(`timeout: ${method}`)), 10000); });
try { const init = await request("initialize", { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "offline-smoke", version: "1" } }); if (init.result?.serverInfo?.name !== "factorio-codex") throw new Error("wrong server metadata"); child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }) + "\n"); const listed = await request("tools/list"); const tools = listed.result.tools; const names = tools.map((t: any) => t.name).sort(); if (JSON.stringify(names) !== JSON.stringify(expected)) throw new Error(`tool mismatch: ${names}`); if (JSON.stringify(tools).match(/agent_id|background|image|lua|console/i)) throw new Error("forbidden schema/content exposed"); const status = await request("tools/call", { name: "connect_status", arguments: {} }); if (!status.result?.content?.[0]?.text?.startsWith("Offline:")) throw new Error("offline status missing"); console.log("PASS initialize, exact 16 tools, forbidden-schema scan, offline status"); } finally { child.kill(); }
